name: "Build systemtap-runner-ubuntu-24.04"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  SYSTEMTAP_SOURCE_BRANCH: release-5.3
  SYSTEMTAP_INSTALL_PREFIX: /var/systemtap-5.3
  S6_OVERLAY_VERSION: 3.2.1.0

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build systemtap"
        run: |
          docker build -f systemtap-builder/Dockerfile -t systemtap-builder --build-arg SOURCE_BRANCH=${{ env.SYSTEMTAP_SOURCE_BRANCH }} --build-arg INSTALL_PREFIX=${{ env.SYSTEMTAP_INSTALL_PREFIX }} ./systemtap-builder
          mkdir -p /tmp/systemtap-build
          docker run --rm -v /tmp/systemtap-build:/systemtap-builddir systemtap-builder
          cp /tmp/systemtap-build/.systemtap-build.tar.gz ./systemtap-runner/

      - name: "GitHub Packages registry login"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push systemtap-runner-ubuntu-24.04"
        uses: docker/build-push-action@v6
        with:
          push: true
          file: systemtap-runner/ubuntu-24.04.Dockerfile
          tags: tsuereth/systemtap-runner-ubuntu-24.04:latest
          build-args: |
            S6_OVERLAY_VERSION=${{ env.S6_OVERLAY_VERSION }}
            SYSTEMTAP_PREFIX=${{ env.SYSTEMTAP_INSTALL_PREFIX }}
          context: ./systemtap-runner
